#ifndef int _putchar(char c);
#ifndef int _islower(int c);
#ifndef int _isalpha(int c);
#ifndef int _abs(int n);
#ifndef int _isupper(int c);
#ifndef int _isdigit(int c);
#ifndef int _strlen(char *s);
#ifndef void _puts(char *s);
#ifndef char *_strcpy(char *dest, char *src);
#ifndef int _atoi(char *s);
#ifndef char *_strcat(char *dest, char *src);
#ifndef char *_strncat(char *dest, char *src, int n);
#ifndef char *_strncpy(char *dest, char *src, int n);
#ifndef int _strcmp(char *s1, char *s2);
#ifndef char *_memset(char *s, char b, unsigned int n);
#ifndef char *_memcpy(char *dest, char *src, unsigned int n);
#ifndef char *_strchr(char *s, char c);
#ifndef unsigned int _strspn(char *s, char *accept);
#ifndef char *_strpbrk(char *s, char *accept);
#ifndef char *_strstr(char *haystack, char *needle);
